---
apiVersion: v1
kind: ReplicationController
metadata:
  name: secor
spec:
  replicas: 1
  selector:
    app: secor
  template:
    metadata:
      labels:
        app: secor
    spec:
      containers:
      - name: secor
        image: crobox/secor
        ports:
        - containerPort: 9092
        - containerPort: 7203
        - containerPort: 9999
        env:
        - name: ZOOKEEPER_QUORUM
          value: zoo1:2181,zoo2:2181,zoo3:2181
        - name: SECOR_S3_BUCKET
          value: secor-lalala 
        - name: AWS_SECRET_KEY
          value: 
        - name: AWS_ACCESS_KEY
          value: 
        - name: SECOR_GROUP
          value: kafka-persist-1
#        - name: DEBUG
#          value: TRUE
