---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service-1
  labels:
    app: kafka-1
spec:
  ports:
  - port: 9092
    name: kafka-port
    targetPort: 9092
    protocol: TCP
  - port: 7203
    name: jmx-port
    targetPort: 7203
    protocol: TCP
  selector:
    app: kafka-1
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service-2
  labels:
    app: kafka-2
spec:
  ports:
  - port: 9092
    name: kafka-port
    targetPort: 9092
    protocol: TCP
  - port: 7203
    name: jmx-port
    targetPort: 7203
    protocol: TCP
  selector:
    app: kafka-2
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service-3
  labels:
    app: kafka-3
spec:
  ports:
  - port: 9092
    name: kafka-port
    targetPort: 9092
    protocol: TCP
  - port: 7203
    name: jmx-port
    targetPort: 7203
    protocol: TCP
  selector:
    app: kafka-3
  type: LoadBalancer
