---
apiVersion: v1
kind: Service
metadata:
  name: km-service
  labels:
    app: km
spec:
  ports:
  - port: 9000
    name: km-port
    targetPort: 9000
    protocol: TCP
  selector:
    app: km
  type: LoadBalancer

