---
apiVersion: v1
kind: ReplicationController
metadata:
  name: km-controller
spec:
  replicas: 1
  selector:
    app: km
  template:
    metadata:
      labels:
        app: km
    spec:
      containers:
      - name: km
        image: sheepkiller/kafka-manager
        ports:
        - containerPort: 9000
        env:
        - name: ZK_HOSTS
          value: zoo1:2181,zoo2:2181,zoo3:2181
        - name: APPLICATION_SECRET
          value: letmein
        - name: KM_ARGS
          value: -Djava.net.preferIPv4Stack=true
